name: Build exatorrent

on:
  push:
    tags:
      - v*

jobs:
  build:
    if: ${{ github.owner }} == "varbhat"
    runs-on: ubuntu-latest
    permissions: write-all

    container:
      image: "ghcr.io/varbhat/void-container:glibc"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Prepare container
        run: |
          xbps-install -Syu || xbps-install -yu xbps
          xbps-install -yu
      - name: Install Packages
        run: xbps-install -Sy git wget bash make go nodejs cross-x86_64-linux-musl cross-i686-linux-musl cross-aarch64-linux-musl cross-x86_64-w64-mingw32 clang github-cli zstd tar
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build exatorrent for Linux (amd64 and arm64) and Win (amd64)
        run: go mod tidy && make web && make app-linux-amd64 && make app-linux-arm64 && make app-linux-x86 && make app-win-amd64
      - name: Setup crossmac and Build for MacOS
        run: |
          wget "https://github.com/varbhat/crossmac/releases/latest/download/crossmac.tar.zst"
          tar xvf crossmac.tar.zst
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/crossmac/lib/
          export PATH=$(pwd)/crossmac/bin/:$PATH
          make app-darwin-amd64 app-darwin-arm64
      - name: Generate SHA256 Checksum
        run: |
          make checksum
      - name: Publish Releases
        run: |
          git config --global --add safe.directory .
          gh config set prompt disabled
          gh release create $(git tag -l | tail -n1) -t $(git tag -l | tail -n1) -p build/*
