name: Build exatorrent

on:
  push:
    tags:
      - v*

jobs:
  build:
    if: ${{ github.owner }} == "varbhat"
    runs-on: ubuntu-latest

    container:
      image: "ghcr.io/varbhat/void-container:glibc"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Prepare container
        run: |
          xbps-install -Syu || xbps-install -yu xbps
          xbps-install -yu
      - name: Install Packages
        run: xbps-install -Sy git curl bash make go nodejs cross-x86_64-linux-musl cross-aarch64-linux-musl github-cli
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build exatorrent
        run: go mod tidy && make web && make app-linux-amd64 && make app-linux-arm64 && make checksum
      - name: Publish Releases
        run: |
          gh config set prompt disabled
          gh release create $(git tag -l | tail -n1) -t $(git tag -l | tail -n1) -p build/*
